#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
#spring:
#  application:
#    name: service-hi
# cloud:
 #   config:
       #config-server的配置，不需要硬编码config-server的地址，使用service-id去eureka-server获取cong-server的地址
 #      discovery:
 #         enabled: true
 #         service-id: config-server
 #      fail-fast: true
 #      profile: dev
    #注明自己的服务注册中心的地址
    #需要指明spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name 。