server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    #可能比较长，复制的时候请写在一行
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: springcloud-config-server
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          #这是其他项目配置文件的git仓库地址
          uri: https://github.com/baixyan/springcloud-config-profile.git
          searchPaths: origin
          #searchPaths: '{application}'
      label: master